name: flutter_emoji
description: "ðŸ‘‰ A light-weight Emoji ðŸ“¦ for Flutter with all up-to-date emojis ðŸ˜„. Made from ðŸ’¯% â˜• with â¤ï¸!"
version: 2.3.4
homepage: "https://github.com/petehouston/flutter-emoji"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.2.0

dev_dependencies:
  lint: ^1.0.0
  test: ^1.20.1